# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabbngoapp', '0003_resturent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='location',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
